spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql:///test
  profiles:
    active: pro

my:
  value: ${random.value}
  int: ${random.int}
  long: ${random.long}
  uuid: ${random.uuid}
  int.less.than.ten: ${random.int(10)}
  # 100前面和1000后面可以是-,(,[ 等任意符号
  int.in.range: ${random.int-100,1000-}


